name: Firebase Functions CI/CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Authenticate with Firebase
        run: firebase login:ci --interactive --token 1//05gB0zMrBBPovCgYIARAAGAUSNwF-L9IriaImxFLrUcb8qPo7JCk3YcevPNndU4K8ATQGFI5icoOlhiTQHcGJ79UcVJSnLHeDwug
      - name: Install Dependencies
        run: npm install
      - name: Deploy Firebase Functions
        run: firebase deploy --only functions
